### ISSUE TITLE
Some open ended question on the ingestion pipeline

### ISSUE THREAD

**Issue by xtfocus** [Azure-Samples/multimodal-rag-code-execution#40]
Thanks for giving many ideas and sharing processing techniques.
As I can see, currently the pipeline seems to be hosted on it's own dedicated machine/webapp/container app rather than using the Azure Document Skillset API, which makes sense because there are so many intricate details, if-else statements to deal with different kinds of documents.
Is it realistic to expect to replicate this work using just the Skillset API, may be with some custome web api skill, is it worth it? I want your opinions.

**Comment by wknums** [comment]
Hi - In my opinion it would be quite hard to replicate the current ingestion pipeline capabilities using the Skillset (Azure AI Search integrated indexing) api and probably not worth the effort required. However, if you have the time to spend, I think having that code as an optional path available would be of interest to others, as there do not seem to be many good examples for that api available at present...

**Comment by xtfocus** [comment]
> u have the t

Thanks, I totally agree. I will close this issue now.
